name: track_trace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/

  fonts:
     - family: SfPro
       fonts:
        - asset: fonts/SfProDisplay.otf
     - family: BalooBhai
       fonts:
        - asset: fonts/BalooBhai.ttf